### ISSUE TITLE
Improve the `view` command

### ISSUE THREAD

**Issue by ryanlml** [AY2223S1-CS2103-F13-2/tp#109]
to support viewing persons with attributes that contains a specified substring, on top whether it contains a specific word.

Search for words, ie people whose names contain the words "Alex" and "Tan"
```
view n/Alex Tan
> Found 3 results:
> Alex Tan ...
> Alex Chua ...
> Alice Tan ...
```

Search for substring, ie people whose names contain the substring "Alex Tan"
```
view n/"Alex Tan"
> Found 1 result"
> Alex Tan ...
```

**Comment by deepimpactmir** [comment]
Oh. I actually already open an issue on this earlier.

**Comment by ryanlml** [comment]
Apologies
