### ISSUE TITLE
Bug with add when adding existing person without surveys

### ISSUE THREAD

**Issue by KeithPJX** [AY2223S1-CS2103-F13-2/tp#144]
Doing: `add n/Steven p/91234567 e/steven@gmail.com a/Steven Rd g/male b/1999-1-1 ra/Chinese re/Free Thinker s/Test`,
followed by: `add n/Steven p/91234567 e/steven@gmail.com a/Steven Rd g/male b/1999-1-1 ra/Chinese re/Free Thinker`
will result in a success message. I think it should be an error message.

**Comment by deepimpactmir** [comment]
~~huh. Note sure why but, I'm not getting a success message. On my end, it fails since the command format is incorrect. (lacking survey)~~

My bad i didn't pull the latest master. This happens because we only check for equality of surveySets. I can push a fix soon. Thanks for the catch!
