### ISSUE TITLE
Allow phone numbers to contain country codes and limit the max length

### ISSUE THREAD

**Issue by deepimpactmir** [AY2223S1-CS2103-F13-2/tp#203]
I think it is fair to consider this as a bug since `Phone` only checks that the string provided is all numeric. Please let me know your thoughts on whether this is a bug.

**Comment by gqsg** [comment]
I think it is reasonable to limit the max length of phone number, else the tester can enter a very long number and the display will be cut off in the app. As for country code, sorry for my bad english understanding, are you saying that if it is a bug to allow the phone numbers to contain country codes or we should allow phone numbers to contain country code?

**Comment by ryanlml** [comment]
I think adding a country code counts as adding a feature and we can't add new features for v1.4. 

Maybe we can just put it in the user guide that Survin is meant to be used in Singapore only, thus only allowing 8 digit phone numbers that start with 9, 8 or 6. Does that count as a feature? Can we add that? I'm not too sure.

**Comment by KeithPJX** [comment]
Yea I agree with @ryanlml that adding country codes counts as a feature. Limiting the length might be fine though.

**Comment by deepimpactmir** [comment]
Thanks for the inputs! I guess we can add the appropriate warnings in the user guide. What do the rest think about limiting the length of phone number?

**Comment by deepimpactmir** [comment]
Deemed as not a bug since the application still works with long phone numbers
