### ISSUE TITLE
Allow adding duplicate persons

### ISSUE THREAD

**Issue by ryanlml** [AY2223S1-CS2103-F13-2/tp#90]
Currently, Survin does not allow users to `add` people with the same name. For example,
```
add n/John Doe ... s/Shopping survey
> New person added: John Doe ...

add n/John Doe ... s/Academic survey
> (ERROR) This person already exists in the address book
```
This probably contradicts the purpose of Survin, since it is possible to have the same person participate in different surveys. 

As a fix, I suggest we change the definition of `isSamePerson` in the `Person` class. As of now, this method only checks if the names are equal.
```Java
public boolean isSamePerson(Person otherPerson) {
    if (otherPerson == this) {
        return true;
    }

    return otherPerson != null
            && otherPerson.getName().equals(getName());
}
```
Instead, on top of checking equality of `getName()`, we could also check equality of `getSurvey()`, so that we have

```
add n/John Doe ... s/Shopping survey
> New person added: John Doe ... Survey: Shopping survey

add n/John Doe ... s/Academic survey
> New person added: John Doe ... Survey: Academic survey

add n/John Doe ... s/Shopping survey
> (ERROR) This person already exists in the address book
```

as intended. Is this a sufficient fix? I'm unsure if there are other edge cases I've yet to consider.

If this change is alright with everyone, I'll be glad to open a PR.

**Comment by gqsg** [comment]
I think you have brought up a very good point! I agree with you it is possible to have the same person participate in different surveys, and also another scenario I can think of would be two different persons with the same name participate in the same survey.

So I think in our case, to check whether two persons are same or not, we should check for unique attributes such as phone number and email.

**Comment by KeithPJX** [comment]
Yea sounds good to me. Referring to what @NUSDG said.

**Comment by deepimpactmir** [comment]
IMO i think it will be rather confusing for the user to see two entries with the same name in our current iteration with the app.
I suggest we can either

1. Change the UI so that it is clear that the entries pertain to a specific survey. Concretely, we could have field that shows the current survey that we are viewing right now, or,
2. Make it so that we store a list of surveys instead to represent that the same person is on multiple surveys.

**Comment by KeithPJX** [comment]
I think we can implement the simple solution first as mentioned by @ryanlml and think of a better solution in the next milestone.
